import { defineConfig } from 'vite';
import { randomUUID } from 'node:crypto';
import { createGame, applyCommand } from './src/engine.js';

// Le mode local passe par le même moteur que l’API et garde les profils en mémoire.
const sessions=new Map(),recoveries=new Map(),rooms=new Map();
const send=(res,status,data)=>{res.statusCode=status;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(data))};
const cookie=(res,id,age=2592000)=>res.setHeader('Set-Cookie',`cc_session=${id}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${age}`);
function localApi(){return{name:'local-game-api',configureServer(server){server.middlewares.use('/api/game',async(req,res)=>{try{let body={};if(req.method==='POST'){let raw='';for await(const c of req)raw+=c;body=JSON.parse(raw||'{}')}const params=new URL(req.url,'http://localhost').searchParams,action=req.method==='GET'?params.get('action'):body.action,session=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('cc_session='))?.slice(11),profile=sessions.get(session);
if(action==='profile'){const pseudo=String(body.pseudo||'').trim().slice(0,20);if(pseudo.length<2)return send(res,400,{error:'Le pseudo doit contenir au moins 2 caractères.'});if([...recoveries.values()].some(x=>x.profile.pseudo.toLowerCase()===pseudo.toLowerCase()))return send(res,409,{error:'Ce pseudo est déjà réservé.'});const sessionId=randomUUID(),recovery=randomUUID(),p={id:randomUUID(),pseudo,points:0,wins:0,games:0};sessions.set(sessionId,p);recoveries.set(recovery,{profile:p,sessionId});cookie(res,sessionId);return send(res,200,{profile:p,recovery})}
if(action==='resume'){const entry=recoveries.get(body.recovery);if(entry?.profile.pseudo.toLowerCase()!==String(body.pseudo||'').toLowerCase())return send(res,403,{error:'Code de reprise invalide.'});sessions.delete(entry.sessionId);entry.sessionId=randomUUID();sessions.set(entry.sessionId,entry.profile);cookie(res,entry.sessionId);return send(res,200,{profile:entry.profile})}
if(action==='me')return profile?send(res,200,{profile}):send(res,401,{error:'Session absente.'});if(action==='logout'){sessions.delete(session);cookie(res,'',0);return send(res,200,{ok:true})}
if(action==='leaderboard')return send(res,200,{leaderboard:[...recoveries.values()].map(x=>x.profile).sort((a,b)=>b.points-a.points).slice(0,20)});if(!profile)return send(res,401,{error:'Choisis un pseudo pour continuer.'});
if(action==='create'){const c=randomUUID().slice(0,6).toUpperCase(),s={status:'lobby',host:profile.id,settings:{minutes:Number(body.minutes)||60,randomStart:true},players:[{id:profile.id,name:profile.pseudo}],phase:'lobby',turn:0,round:0,log:[{text:`${profile.pseudo} a créé le salon.`,icon:'✦'}]};rooms.set(c,{state:s,version:0});return send(res,200,{code:c,state:s})}
if(action==='join'){const c=String(body.code||'').toUpperCase(),r=rooms.get(c);if(!r)return send(res,404,{error:'Salon introuvable.'});if(r.state.status!=='lobby')return send(res,409,{error:'La partie a déjà commencé.'});if(!r.state.players.some(x=>x.id===profile.id)){if(r.state.players.length>=6)return send(res,409,{error:'Ce salon est complet.'});r.state.players.push({id:profile.id,name:profile.pseudo});r.state.log.unshift({text:`${profile.pseudo} rejoint la partie.`,icon:'✦'});r.version++}return send(res,200,{code:c,state:r.state})}
if(action==='state'){const c=params.get('code'),r=rooms.get(c);if(!r||!r.state.players.some(x=>x.id===profile?.id))return send(res,404,{error:'Salon inaccessible.'});return send(res,200,{state:r.state,version:r.version})}
if(action==='command'){const r=rooms.get(String(body.code||'').toUpperCase());if(!r||!r.state.players.some(x=>x.id===profile?.id))return send(res,404,{error:'Salon inaccessible.'});if(Number(body.version)!==r.version)return send(res,409,{error:'La partie a évolué. Actualisation…'});const wasFinished=r.state.status==='finished';try{applyCommand(r.state,profile.id,body.command,body,['roll','timeout'].includes(body.command)?[1+Math.floor(Math.random()*6),1+Math.floor(Math.random()*6)]:undefined)}catch(e){return send(res,400,{error:e.message})}if(!wasFinished&&r.state.status==='finished')for(const result of r.state.results){const player=[...recoveries.values()].find(x=>x.profile.id===result.id)?.profile;if(player){player.points+=result.points;player.games++;if(result.id===r.state.results[0].id)player.wins++}}r.version++;return send(res,200,{state:r.state,version:r.version})}
return send(res,400,{error:'Action inconnue.'})}catch(e){console.error(e);return send(res,500,{error:'Erreur du serveur local.'})}})}}}
export default defineConfig({plugins:[localApi()],server:{host:'0.0.0.0'}});
