import test from 'node:test';
import assert from 'node:assert/strict';
import { createGame, applyCommand, ECONOMY } from './engine.js';

const START=ECONOMY.startCash;

const players=[{id:'a',name:'Alix'},{id:'b',name:'Basile'}];
const started=()=>{const s={status:'lobby',host:'a',settings:{minutes:60},players,phase:'lobby',turn:0,round:0,log:[]};applyCommand(s,'a','start');return s};

test('le plateau contient 40 cases et chaque joueur reçoit le capital de départ',()=>{const s=createGame(players,60);assert.equal(s.board.length,40);assert.deepEqual(s.players.map(p=>p.cash),[START,START])});
test('un joueur achète une propriété et son rival paie le loyer',()=>{const s=started();applyCommand(s,'a','roll',{},[2,3]);assert.equal(s.phase,'decision');applyCommand(s,'a','buy');assert.equal(s.board[5].owner,'a');applyCommand(s,'a','end');applyCommand(s,'b','roll',{},[2,3]);assert.equal(s.players[1].cash,START-ECONOMY.transportRents[1]);assert.equal(s.players[0].cash,START-200+ECONOMY.transportRents[1])});
test('le refus ouvre une enchère à 80 %, avec surenchère de 5 %',()=>{const s=started();applyCommand(s,'a','roll',{},[2,3]);applyCommand(s,'a','pass');assert.equal(s.phase,'auction');applyCommand(s,'a','auction-bid',{amount:160});applyCommand(s,'b','auction-bid',{amount:168});applyCommand(s,'a','auction-pass');assert.equal(s.board[5].owner,'b');assert.equal(s.players[1].cash,START-168);assert.equal(s.phase,'end')});
test('trois doubles consécutifs envoient au Commissariat',()=>{const s=started();s.cityDeck=Array(12).fill(['Carte test','cash:1']);for(let i=0;i<3;i++){applyCommand(s,'a','roll',{},[1,1]);if(i<2)applyCommand(s,'a','end')}assert.equal(s.players[0].pos,10);assert.equal(s.players[0].jailed,1)});
test('construire demande le groupe complet',()=>{const s=started();s.board[1].owner='a';assert.throws(()=>applyCommand(s,'a','build',{tile:1}),/groupe entier/)});
test('le stock commun de maisons baisse à chaque construction',()=>{const s=started();s.board[1].owner='a';s.board[3].owner='a';applyCommand(s,'a','build',{tile:1});applyCommand(s,'a','build',{tile:3});assert.equal(s.bank.houses,30);assert.deepEqual([s.board[1].level,s.board[3].level],[1,1])});
test('une dette peut être réglée après une hypothèque',()=>{const s=started();s.board[1].owner='a';s.players[0].cash=30;s.pendingDebt={debtor:'a',creditor:'bank',amount:60,reason:'loyer'};s.phase='debt';applyCommand(s,'a','debt-mortgage',{tile:1});applyCommand(s,'a','debt-settle');assert.equal(s.players[0].cash,10);assert.equal(s.pendingDebt,null);assert.equal(s.board[1].mortgage,true)});
test('un échange de titres attend l’accord du destinataire',()=>{const s=started();s.board[1].owner='a';s.board[3].owner='b';s.players[0].releaseCards=1;applyCommand(s,'a','trade-propose',{target:'b',giveCash:100,getCash:50,giveTiles:[1],getTiles:[3],giveCards:1});assert.equal(s.board[1].owner,'a');applyCommand(s,'b','trade-accept');assert.equal(s.board[1].owner,'b');assert.equal(s.board[3].owner,'a');assert.equal(s.players[0].cash,START-50);assert.equal(s.players[1].cash,START+50);assert.equal(s.players[0].releaseCards,0)});
test('une dette créée par une carte hors tour revient au joueur actif',()=>{const s=started();s.settings.debtLimit=0;s.cityDeck=Array(12).fill(['Solidarité','payeach:25']);s.players[1].cash=0;s.board[1].owner='b';applyCommand(s,'a','roll',{},[1,1]);assert.equal(s.phase,'debt');assert.equal(s.pendingDebt.debtor,'b');applyCommand(s,'b','debt-mortgage',{tile:1});applyCommand(s,'b','debt-settle');assert.equal(s.turn,0);assert.equal(s.phase,'bonus');assert.equal(s.players[0].cash,START+25);assert.equal(s.players[1].cash,15)});
test('la faillite au dernier autre joueur termine la partie et transfère ses titres',()=>{const s=started();s.board[1].owner='b';s.players[1].cash=20;s.pendingDebt={debtor:'b',creditor:'a',amount:80,reason:'loyer',resumeTurn:0,resumePhase:'end',resumeDouble:false};s.phase='debt';applyCommand(s,'b','debt-bankrupt');assert.equal(s.status,'finished');assert.equal(s.turn,0);assert.equal(s.board[1].owner,'a');assert.equal(s.results[0].name,'Alix');assert.equal(s.results[0].points,Math.floor((START+20+80)/10)+300)});
test('une carte ou la case Commissariat annule la relance même sur double',()=>{const s=started();s.cityDeck=Array(12).fill(['Convocation','jail']);applyCommand(s,'a','roll',{},[1,1]);assert.equal(s.players[0].jailed,1);assert.equal(s.phase,'end');const t=started();t.players[0].pos=28;applyCommand(t,'a','roll',{},[1,1]);assert.equal(t.players[0].pos,10);assert.equal(t.phase,'end')});
