import './style.css';
import './cartoon.css';
import './polish.css';
import { gameMarkup, propertyMarkup, rulesMarkup } from './game-view.js';
import { asset, decorateAssets } from './assets.js';
const root=document.querySelector('#app'),storage=localStorage;
let me=null,roomCode=null,state=null,version=0,poll=null,busy=false,notice='',anim=true,tradeOpen=false,inspectedTile=null,boardZoomed=false,mobileTab='board',seenLog=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(action,data={},get=false){const url=get?`/api/game?action=${action}${data.code?'&code='+encodeURIComponent(data.code):''}`:'/api/game';let r=await fetch(url,{method:get?'GET':'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:get?undefined:JSON.stringify({action,...data})});let x=await r.json();if(!r.ok)throw Error(x.error||'Erreur réseau');return x}
function msg(s){notice=s;document.querySelector('.toast')?.remove();let el=document.createElement('div');el.className='toast';el.setAttribute('role','status');el.textContent=s;document.body.append(el);setTimeout(()=>{if(el.isConnected)el.remove();if(notice===s)notice=''},7000)}
function setProfile(p){me=p;storage.setItem('cc_profile',JSON.stringify(p));storage.removeItem('cc_token');home()}
function showRecovery(code){const backdrop=document.createElement('div');backdrop.className='deal-backdrop recovery-backdrop';backdrop.innerHTML=`<section class="deal-dialog recovery-dialog" role="dialog" aria-modal="true" aria-label="Code de reprise"><div class="panel-kicker">TON IDENTITÉ DE JOUEUR</div><h2>Garde ton code de reprise</h2><p>Ce code permet de retrouver ton pseudo et tes points sur un autre appareil. Conserve-le en privé : il ne sera plus affiché.</p><code>${esc(code)}</code><div class="deal-actions"><button class="btn outline" id="copy-recovery">Copier le code</button><button class="btn gold" id="close-recovery">J’ai sauvegardé le code</button></div></section>`;document.body.append(backdrop);backdrop.querySelector('#copy-recovery').onclick=async()=>{try{await navigator.clipboard.writeText(code);msg('Code copié')}catch{msg('Copie le code affiché')}};backdrop.querySelector('#close-recovery').onclick=()=>backdrop.remove()}
function home(){clearInterval(poll);document.querySelectorAll('.deal-backdrop').forEach(el=>el.remove());roomCode=null;state=null;tradeOpen=false;storage.removeItem('cc_room');render()}
function render(){if(state?.status!=='playing'){document.querySelectorAll('.info-dialog').forEach(el=>el.remove());inspectedTile=null}const result=!me?renderAuth():!state?renderHome():state.status==='lobby'?renderLobby():state.status==='finished'?renderResults():renderGame();Promise.resolve(result).then(()=>decorateAssets(root));return result}
async function leaderboard(){try{return(await api('leaderboard')).leaderboard}catch{return []}}
async function renderAuth(){let leaders=await leaderboard();root.innerHTML=`<main class="entry"><div class="entry-art"><div class="sun"></div><div class="cityline">${Array.from({length:15},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div><div class="art-tag">JEU DE SOCIÉTÉ · EN LIGNE</div><div class="brand">CITÉ<br><em>CAPITALE</em></div><p>Petits loyers. Grandes embrouilles.</p><div class="art-stats"><span>2—6 <small>JOUEURS</small></span><span>40 <small>CASES À CONQUÉRIR</small></span><span>100 % <small>MAUVAISE FOI</small></span></div></div><section class="entry-panel"><div class="panel-kicker">BIENVENUE EN VILLE</div><h1>Tes potes.<br/>Tes rues.<br/>Ton petit empire.</h1><p class="muted">Un pseudo, une bande de potes et beaucoup de mauvaises excuses pour ne pas payer le loyer.</p><form id="profile-form"><label for="pseudo">TON PSEUDO</label><div class="input-row"><span>✦</span><input id="pseudo" maxlength="20" minlength="2" placeholder="Ex. BaronDuCanapé" required autocomplete="nickname"/><button class="btn gold" type="submit">Entrer <b>↗</b></button></div></form><details class="resume"><summary>J’ai déjà un code de reprise</summary><form id="resume-form"><input name="pseudo" placeholder="Pseudo" required/><input name="recovery" placeholder="Code de reprise" required/><button class="btn outline">Récupérer mon profil</button></form></details><div class="leaderboard"><div class="section-head"><span>LE CLASSEMENT</span><span>◉ EN VILLE</span></div>${leaders.length?leaders.slice(0,5).map((p,i)=>`<div class="rank-row"><b class="rank-num">${String(i+1).padStart(2,'0')}</b><span>${esc(p.pseudo)}</span><small>${Number(p.wins)||0} victoires</small><strong>${Number(p.points).toLocaleString('fr-FR')} pts</strong></div>`).join(''):'<div class="empty">Le trône est libre. Même pour les mauvais perdants.</div>'}</div><footer>Une partie privée, un pseudo à la fois.<span>© CITÉ CAPITALE</span></footer></section></main>`;
 document.querySelector('#profile-form').onsubmit=async e=>{e.preventDefault();try{let x=await api('profile',{pseudo:document.querySelector('#pseudo').value.trim()});setProfile(x.profile);showRecovery(x.recovery)}catch(err){msg(err.message)}};
 document.querySelector('#resume-form').onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.currentTarget));try{let x=await api('resume',d);setProfile(x.profile)}catch(err){msg(err.message)}};}
function renderHome(){let leaders='';root.innerHTML=`<main class="home"><header class="topbar"><a class="wordmark" href="#" id="logo">CITÉ <em>CAPITALE</em></a><div class="user-chip"><div class="avatar">${esc(me.pseudo.slice(0,1).toUpperCase())}</div><div>${esc(me.pseudo)}<small>${Number(me.points||0).toLocaleString('fr-FR')} points</small></div><button id="logout" title="Changer de pseudo">↗</button></div></header><section class="welcome"><div><div class="panel-kicker">TON QUARTIER GÉNÉRAL</div><h1>Bienvenue au<br/><em>club des proprios.</em></h1><p>Achète la rue. Chamboule le quartier. Fais payer tes potes avec le sourire.</p></div><div class="welcome-stamp"><span>CC</span><small>ÉDITION<br/>ENTRE AMIS</small></div></section><div class="home-grid"><section class="create-card"><div class="card-icon">${asset("house")}</div><div class="panel-kicker">NOUVELLE PARTIE</div><h2>Je crée la partie</h2><p>Crée une ville privée et invite tes amis avec un code.</p><label>DURÉE DE LA PARTIE</label><select id="minutes"><option value="60">60 minutes · classique</option><option value="45">45 minutes · rapide</option><option value="90">90 minutes · longue</option></select><button class="btn gold full" id="create">Créer un salon <b>↗</b></button><div class="tiny">2 à 6 joueurs · gratuit · privé</div></section><section class="join-card"><div class="panel-kicker">REJOINDRE UNE PARTIE</div><h2>Je rejoins les potes</h2><p>Entre le code partagé par l’hôte de la partie.</p><form id="join-form"><label>CODE DU SALON</label><div class="input-row"><input id="room-code" maxlength="6" placeholder="A1B2C3" required/><button class="btn outline">Rejoindre <b>↗</b></button></div></form><div class="invite-note"><span>◎</span> Les salons sont privés. Seuls les joueurs avec le code peuvent entrer.</div></section></div><section class="global-rank"><div><div class="panel-kicker">LES GRANDES FORTUNES</div><h2>Classement des joueurs</h2></div><div class="rank-list" id="rank-list"><div class="empty">Chargement…</div></div></section><footer class="home-footer">CITÉ CAPITALE <span>UN PLATEAU. VOS RÈGLES. VOTRE HISTOIRE.</span></footer></main>`;
document.querySelector('#logout').onclick=async()=>{try{await api('logout')}catch{}me=null;storage.removeItem('cc_profile');render()};document.querySelector('#create').onclick=async()=>{try{let x=await api('create',{minutes:Number(document.querySelector('#minutes').value)});enterRoom(x.code,x.state)}catch(e){msg(e.message)}};document.querySelector('#join-form').onsubmit=async e=>{e.preventDefault();try{let x=await api('join',{code:document.querySelector('#room-code').value.trim()});enterRoom(x.code,x.state)}catch(err){msg(err.message)}};
api('leaderboard').then(x=>{let el=document.querySelector('#rank-list');if(!el)return;el.innerHTML=x.leaderboard.length?x.leaderboard.slice(0,7).map((p,i)=>`<div class="rank-row"><b class="rank-num">${String(i+1).padStart(2,'0')}</b><span>${esc(p.pseudo)}</span><small>${p.games} parties · ${p.wins} victoires</small><strong>${Number(p.points).toLocaleString('fr-FR')} pts</strong></div>`).join(''):'<div class="empty">Joue une partie pour inscrire ton nom.</div>'}).catch(()=>{});}
function enterRoom(c,s){roomCode=c;state=s;version=0;mobileTab='board';seenLog=s?.log?.length||0;storage.setItem('cc_room',c);render();clearInterval(poll);poll=setInterval(refresh,1400)}
async function refresh(){if(!roomCode||busy)return;try{let x=await api('state',{code:roomCode},true);if(x.version!==version){const previous=state;state=x.state;version=x.version;render();animateTransition(previous,state);notifyTurn(previous,state)}}catch(e){if(e.message!=='Ce n’est pas ton tour.')console.debug(e)}}
async function command(cmd,payload){if(busy)return;busy=true;try{let data=payload===undefined?{}:typeof payload==='object'?payload:{tile:Number(payload)};let x=await api('command',{code:roomCode,command:cmd,version,...data});const previous=state;state=x.state;version=x.version;notice='';render();animateTransition(previous,state)}catch(e){notice=e.message;await refresh();msg(notice)}finally{busy=false}}
function renderLobby(){const host=me&&state.host===me.id;root.innerHTML=`<main class="lobby-page"><header class="topbar"><a class="wordmark" href="#">CITÉ <em>CAPITALE</em></a><button class="btn ghost" id="leave">← Quitter le salon</button></header><section class="lobby-hero"><div class="panel-kicker">SALON PRIVÉ · EN ATTENTE</div><h1>La bande se rassemble.</h1><p>Partage ce code avec les personnes que tu veux inviter.</p><div class="invite-code"><span>${roomCode}</span><button id="copy">Copier le code</button></div><div class="invite-link"><span id="invite-url"></span><button class="btn outline" id="share-link">${navigator.share?'Partager le lien':'Copier le lien'}</button></div></section><section class="lobby-bottom"><div class="player-roster"><div class="section-head"><span>LES JOUEURS</span><span>${state.players.length} / 6</span></div><div class="roster">${state.players.map((p,i)=>`<article class="roster-card" style="--accent:${p.color}"><div class="roster-token">${asset(["frog","fox","panda","octopus","chick","koala"][i])}</div><div><strong>${esc(p.name)}</strong><small>${p.id===state.host?'HÔTE':'PRÊT À JOUER'}</small></div><span class="roster-num">0${i+1}</span></article>`).join('')}${Array.from({length:Math.max(0,2-state.players.length)},()=>'<article class="roster-card vacant"><span>＋</span><small>EN ATTENTE D’UN AMI</small></article>').join('')}</div></div><aside class="launch-card"><div class="panel-kicker">RÈGLES DE LA PARTIE</div><div class="rule-line"><span>⌖</span><div><b>Capital de départ</b><small>1 500 ¤ par joueur</small></div></div><div class="rule-line"><span>◷</span><div><b>Durée</b><small>${state.settings.minutes} minutes</small></div></div><div class="rule-line"><span>♙</span><div><b>Objectif</b><small>Finir avec le plus grand patrimoine</small></div></div>${host?`<button class="btn gold full launch" id="start" ${state.players.length<2?'disabled':''}>Lancer la partie <b>↗</b></button><small class="launch-hint">${state.players.length<2?'Il faut au moins 2 joueurs.':'Tout le monde est prêt ?'}</small>`:`<div class="waiting-host"><i></i> En attente du lancement par ${esc(state.players.find(p=>p.id===state.host)?.name||'l’hôte')}</div>`}</aside></section></main>`;
document.querySelector('#leave').onclick=home;document.querySelector('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(roomCode);msg('Code copié !')}catch{msg(`Code à partager : ${roomCode}`)}};const inviteUrl=`${location.origin}/?salon=${roomCode}`;document.querySelector('#invite-url').textContent=inviteUrl;document.querySelector('#share-link').onclick=async()=>{try{if(navigator.share)await navigator.share({title:'Cité Capitale',text:`Rejoins ma partie de Cité Capitale (salon ${roomCode})`,url:inviteUrl});else{await navigator.clipboard.writeText(inviteUrl);msg('Lien copié !')}}catch(e){if(e?.name!=='AbortError')msg(`Lien à partager : ${inviteUrl}`)}};document.querySelector('#start')?.addEventListener('click',()=>command('start'));}
function renderResults(){document.querySelectorAll('.deal-backdrop').forEach(el=>el.remove());api('me',{},true).then(x=>{me=x.profile;storage.setItem('cc_profile',JSON.stringify(me))}).catch(()=>{});const results=state.results||[],winner=results[0],mine=results.find(result=>result.id===me.id);root.innerHTML=`<main class="results-page"><div class="confetti" aria-hidden="true">${Array.from({length:28},(_,i)=>`<i style="--x:${(i*37)%100}%;--delay:${(i*13)%20/10}s;--rotate:${(i*47)%360}deg"></i>`).join('')}</div><header class="topbar"><a class="wordmark" href="#" id="results-logo">CITÉ <em>CAPITALE</em></a><span class="panel-kicker">PARTIE TERMINÉE · SALON ${esc(roomCode)}</span></header><section class="results-hero">${asset("trophy","result-hero-asset")}<div class="panel-kicker">LE CLASSEMENT FINAL</div><h1>On applaudit<br/><em>le roi du quartier !</em></h1><p><strong>${esc(winner?.name||'')}</strong> termine en tête. Ton pseudo gagne <b>${Number(mine?.points||0).toLocaleString('fr-FR')} points</b> pour cette partie.</p></section><section class="results-list">${results.map((result,index)=>`<article class="result-card ${index===0?'winner':''} ${result.id===me.id?'my-result':''}"><span class="result-rank">${String(index+1).padStart(2,'0')}</span><div><strong>${esc(result.name)}</strong><small>${result.score<0?'En faillite':`${Math.round(result.score).toLocaleString('fr-FR')} ¤ de patrimoine`}</small><span class="result-badge">✦ ${esc(result.highlight||'Explorateur')}</span></div><b>+${Number(result.points).toLocaleString('fr-FR')} pts</b></article>`).join('')}</section><div class="result-actions"><button class="btn gold" id="results-replay">Créer une nouvelle partie ↗</button><button class="btn outline" id="results-home">Retour à l’accueil</button></div></main>`;document.querySelector('#results-home').onclick=home;document.querySelector('#results-logo').onclick=e=>{e.preventDefault();home()};document.querySelector('#results-replay').onclick=async()=>{try{const x=await api('create',{minutes:state.settings?.minutes||60});enterRoom(x.code,x.state)}catch(e){msg(e.message)}}}
function animateTransition(before,after){if(!anim||matchMedia('(prefers-reduced-motion: reduce)').matches||!before?.players||after?.status!=='playing')return;const board=document.querySelector('.board'),tiles=board?.querySelectorAll('.tile');if(!board||tiles?.length!==40)return;const boardRect=board.getBoundingClientRect(),center=index=>{const rect=tiles[index].getBoundingClientRect();return {x:rect.left-boardRect.left+rect.width/2,y:rect.top-boardRect.top+rect.height/2}};for(const player of after.players){const previous=before.players.find(p=>p.id===player.id);if(previous?.pos==null||previous.pos===player.pos)continue;const distance=(player.pos-previous.pos+40)%40,indices=(player.jailed&&player.pos===10)||distance>16?[previous.pos,player.pos]:Array.from({length:distance+1},(_,i)=>(previous.pos+i)%40);const token=document.createElement('span');token.className='travel-token';token.style.background=player.color;token.textContent=player.name.slice(0,1).toUpperCase();board.append(token);const points=indices.map((index,i)=>{const pos=center(index);return {offset:i/(indices.length-1),transform:`translate(${pos.x-11}px, ${pos.y-11}px) scale(${i===indices.length-1?1.25:1})`}});const animation=token.animate(points,{duration:Math.min(1600,350+indices.length*105),easing:'ease-in-out',fill:'forwards'});animation.onfinish=()=>token.remove()}if(before.log?.[0]?.text!==after.log?.[0]?.text&&after.log?.slice(0,3).some(entry=>entry.text.includes(' paie '))){const burst=document.createElement('span');burst.className='coin-burst';for(let i=0;i<8;i++){const coin=document.createElement('i'),angle=i*Math.PI/4;coin.style.setProperty('--dx',`${Math.cos(angle)*72}px`);coin.style.setProperty('--dy',`${Math.sin(angle)*72}px`);burst.append(coin)}board.append(burst);setTimeout(()=>burst.remove(),950)}}
function secondsLeft(){if(!state?.turnStartedAt)return null;return Math.max(0,(state.settings?.turnSeconds||90)-Math.floor((Date.now()-state.turnStartedAt)/1000))}
function clockLabel(seconds){if(seconds==null)return '--:--';return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}
let timeoutAttemptVersion=-1,timeoutAttemptAt=0;
function tickClock(){const clock=document.querySelector('#turn-countdown');if(!clock||state?.status!=='playing')return;const left=secondsLeft();clock.textContent=clockLabel(left);clock.classList.toggle('urgent',left!==null&&left<=15);if(left===0&&!busy&&(timeoutAttemptVersion!==version||Date.now()-timeoutAttemptAt>5000)){timeoutAttemptVersion=version;timeoutAttemptAt=Date.now();command('timeout')}}
function titleChoices(ownerId,name){const items=state.board.map((tile,index)=>({tile,index})).filter(x=>x.tile.owner===ownerId&&!x.tile.level);return `<fieldset><legend>${name}</legend>${items.length?items.map(({tile,index})=>`<label class="deal-title"><input type="checkbox" value="${index}"/>${esc(tile.name)} <small>${tile.price} ¤${tile.mortgage?' · hypothéqué':''}</small></label>`).join(''):'<p class="muted">Aucun titre échangeable.</p>'}</fieldset>`}
function tradeMarkup(){const offer=state.trade;if(offer){if(me.id!==offer.from&&me.id!==offer.to)return '';const from=state.players.find(p=>p.id===offer.from),to=state.players.find(p=>p.id===offer.to),names=indices=>indices.map(i=>state.board[i]?.name).filter(Boolean).map(esc).join(', ')||'aucun titre';return `<div class="deal-backdrop"><section class="deal-dialog" aria-label="Proposition d’échange"><div class="panel-kicker">PROPOSITION D’ÉCHANGE</div><h2>${esc(from?.name)} ⇄ ${esc(to?.name)}</h2><div class="deal-columns"><p><b>${esc(from?.name)} donne</b><br/>${offer.giveCash} ¤ · ${names(offer.giveTiles)}${offer.giveCards?` · ${offer.giveCards} carte(s) Libération`:''}</p><p><b>${esc(to?.name)} donne</b><br/>${offer.getCash} ¤ · ${names(offer.getTiles)}${offer.getCards?` · ${offer.getCards} carte(s) Libération`:''}</p></div><div class="deal-actions">${me.id===offer.to?'<button class="btn gold" id="trade-accept">Accepter</button><button class="btn outline" id="trade-reject">Refuser</button>':'<button class="btn outline" id="trade-cancel">Annuler ma proposition</button>'}</div></section></div>`}
if(!tradeOpen)return '';const others=state.players.filter(p=>p.id!==me.id&&!p.bankrupt),target=others[0];if(!target)return '';return `<div class="deal-backdrop"><form class="deal-dialog" id="trade-form"><div class="panel-kicker">NÉGOCIATION</div><h2>Proposer un échange</h2><label for="trade-target">Avec qui ?</label><select id="trade-target">${others.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select><div class="deal-columns"><div><label>Tu donnes (¤)</label><input id="give-cash" type="number" min="0" max="${state.players.find(p=>p.id===me.id)?.cash||0}" value="0"/><label>Cartes Libération</label><input id="give-cards" type="number" min="0" max="${state.players.find(p=>p.id===me.id)?.releaseCards||0}" value="0"/><div id="give-titles">${titleChoices(me.id,'Tes titres')}</div></div><div><label>Tu demandes (¤)</label><input id="get-cash" type="number" min="0" max="${target.cash}" value="0"/><label>Cartes Libération</label><input id="get-cards" type="number" min="0" max="${target.releaseCards||0}" value="0"/><div id="get-titles">${titleChoices(target.id,'Ses titres')}</div></div></div><div class="deal-actions"><button class="btn gold" type="submit">Envoyer la proposition</button><button class="btn outline" type="button" id="trade-close">Fermer</button></div></form></div>`}
function bindTrade(){document.querySelectorAll('.deal-backdrop').forEach(el=>el.remove());const canOffer=state.status==='playing'&&!state.trade&&state.players[state.turn]?.id===me.id&&['roll','end','bonus'].includes(state.phase);if(canOffer){document.querySelector('.game-tools')?.insertAdjacentHTML('beforeend','<button id="trade-open">⇄ Échanger</button>');document.querySelector('#trade-open').onclick=()=>{tradeOpen=true;renderGame()}}document.body.insertAdjacentHTML('beforeend',tradeMarkup());document.querySelector('#trade-close')?.addEventListener('click',()=>{tradeOpen=false;document.querySelector('.deal-backdrop')?.remove()});document.querySelector('#trade-target')?.addEventListener('change',e=>{const p=state.players.find(x=>x.id===e.target.value);document.querySelector('#get-titles').innerHTML=titleChoices(p.id,'Ses titres');document.querySelector('#get-cash').max=p.cash;document.querySelector('#get-cards').max=p.releaseCards||0});document.querySelector('#trade-form')?.addEventListener('submit',e=>{e.preventDefault();const checked=id=>[...document.querySelectorAll(`#${id} input:checked`)].map(el=>Number(el.value));const value=id=>Math.max(0,Number(document.querySelector('#'+id).value)||0);const payload={target:document.querySelector('#trade-target').value,giveCash:value('give-cash'),getCash:value('get-cash'),giveCards:value('give-cards'),getCards:value('get-cards'),giveTiles:checked('give-titles'),getTiles:checked('get-titles')};tradeOpen=false;document.querySelector('.deal-backdrop')?.remove();command('trade-propose',payload)});for(const action of ['trade-accept','trade-reject','trade-cancel'])document.querySelector('#'+action)?.addEventListener('click',()=>command(action))}
function showInfo(content, onClose=()=>{}) {
  document.querySelectorAll('.info-dialog').forEach(el=>el.remove());
  const previousFocus=document.activeElement;
  const dialog=document.createElement('dialog');dialog.className='info-dialog';
  dialog.innerHTML='<button class="dialog-close" aria-label="Fermer la fiche">×</button>'+content;
  document.body.append(dialog);decorateAssets(dialog);
  const heading=dialog.querySelector('h2');if(heading){heading.id='info-title';dialog.setAttribute('aria-labelledby','info-title')}
  const close=()=>{dialog.close();dialog.remove();onClose();if(previousFocus?.isConnected)previousFocus.focus()};
  dialog.querySelector('.dialog-close').onclick=close;
  dialog.addEventListener('cancel',event=>{event.preventDefault();close()});
  dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)close()}});
  dialog.showModal();return dialog;
}
function showProperty(index) {
  inspectedTile=index;
  const dialog=showInfo(propertyMarkup(state,me,index),()=>{inspectedTile=null});
  dialog.querySelectorAll('[data-property-action]').forEach(button=>button.onclick=()=>{
    const action=button.dataset.propertyAction,tile=Number(button.dataset.propertyIndex);
    inspectedTile=null;dialog.close();dialog.remove();command(action,{tile});
  });
}
function renderGame() {
  const previousWrap=document.querySelector('.board-wrap.zoomed'),keepScroll=previousWrap?{left:previousWrap.scrollLeft,pos:previousWrap.dataset.pos}:null;
  root.innerHTML=gameMarkup({state,me,roomCode,clock:clockLabel(secondsLeft()),anim});
  if(wideBoard.matches){const banner=document.querySelector('.turn-banner'),center=document.querySelector('.board-center');banner.classList.add('in-board');center.classList.add('has-actions');center.querySelector('.dice-area').after(banner)}
  bindTrade();
  const tradeButton=document.querySelector('#trade-open');if(tradeButton){tradeButton.className='btn gold';tradeButton.textContent='🤝 Échanger avec un pote'}
  if(narrowScreen.matches)setupMobile();
  for(const action of ['debt-settle','debt-bankrupt','bail','release','buy','pass','auction-pass','end'])document.querySelector('#'+action)?.addEventListener('click',()=>command(action));
  document.querySelector('#roll')?.addEventListener('click',event=>{event.currentTarget.disabled=true;document.querySelector('.board')?.classList.add('rolling');setTimeout(()=>command('roll').finally(()=>{document.querySelector('.board')?.classList.remove('rolling');const roll=document.querySelector('#roll');if(roll)roll.disabled=false}),420)});
  document.querySelector('#bid')?.addEventListener('click',()=>command('auction-bid',{amount:document.querySelector('#bid-amount').value}));
  document.querySelectorAll('[data-tile-card]').forEach(button=>button.addEventListener('click',()=>showProperty(Number(button.dataset.tileCard))));
  document.querySelector('#exit-game').onclick=home;
  document.querySelector('#game-logo').onclick=event=>{event.preventDefault();home()};
  document.querySelector('#copy-game').onclick=async()=>{try{await navigator.clipboard.writeText(roomCode);msg('Code copié. Rameute la bande !')}catch{msg('Le code du salon : '+roomCode)}};
  document.querySelector('#motion').onclick=()=>{anim=!anim;document.body.classList.toggle('reduce-motion',!anim);render()};
  document.querySelector('#rules').onclick=()=>showInfo(rulesMarkup);
  const boardWrap=document.querySelector('.board-wrap');
  boardWrap.insertAdjacentHTML('beforebegin','<button id="board-zoom" class="btn outline board-zoom" aria-pressed="'+boardZoomed+'">'+(boardZoomed?'Vue complète du plateau':'Agrandir le plateau ⤢')+'</button>');
  boardWrap.classList.toggle('zoomed',boardZoomed);
  document.querySelector('#board-zoom').onclick=event=>{boardZoomed=!boardZoomed;boardWrap.classList.toggle('zoomed',boardZoomed);event.currentTarget.setAttribute('aria-pressed',String(boardZoomed));event.currentTarget.textContent=boardZoomed?'Vue complète du plateau':'Agrandir le plateau ⤢';if(boardZoomed)centerCurrentTile(boardWrap)};
  // Plateau agrandi : on garde le défilement de l'utilisateur, sauf si le pion actif a bougé.
  const activePos=String(state.players[state.turn]?.pos??'');boardWrap.dataset.pos=activePos;
  if(boardZoomed){if(keepScroll&&keepScroll.pos===activePos)boardWrap.scrollLeft=keepScroll.left;else centerCurrentTile(boardWrap)}
  decorateAssets(root);
  if(inspectedTile!==null)showProperty(inspectedTile);
}
function centerCurrentTile(wrap){const tile=wrap.querySelector('.tile.current');if(tile)wrap.scrollLeft=tile.offsetLeft-wrap.clientWidth/2+tile.offsetWidth/2}
// Mobile : une page par onglet (plateau, terrains, journal, options) et une barre d'onglets en bas.
function setupMobile(){
  const page=document.querySelector('.game-page'),rail=document.querySelector('.activity-rail'),banner=document.querySelector('.turn-banner');
  page.classList.add('mobile-game','tab-'+mobileTab);
  rail.querySelector('.property-panel').after(document.querySelector('.goal-card'));
  const more=document.createElement('section');more.className='more-panel';
  more.innerHTML=`<div class="section-head"><span>OPTIONS</span></div><div class="more-room"><small>Code du salon</small><b>${esc(roomCode)}</b></div>`;
  more.append(document.querySelector('.game-tools'));
  more.insertAdjacentHTML('beforeend','<button class="btn outline full" id="exit-mobile">Quitter la partie</button>');
  rail.append(more);more.querySelector('#exit-mobile').onclick=home;
  const trade=document.querySelector('#trade-open');if(trade){trade.textContent='🤝 Échanger';trade.classList.add('trade-mini');banner.append(trade)}
  if(mobileTab==='log')seenLog=state.log.length;
  const mine=state.board.filter(t=>t.owner===me.id).length,unread=Math.max(0,state.log.length-seenLog);
  const tabs=[['board','Plateau','dice-5',0],['props','Terrains','house',mine],['log','Journal','city-card',unread],['more','Options','event-card',0]];
  page.insertAdjacentHTML('beforeend',`<nav class="mobile-tabs" aria-label="Sections de la partie">${tabs.map(([id,label,icon,badge])=>`<button type="button" data-tab="${id}" aria-pressed="${mobileTab===id}">${asset(icon)}<span>${label}</span>${badge?`<b class="${id==='log'?'unread':''}">${badge>99?'99+':badge}</b>`:''}</button>`).join('')}</nav>`);
  page.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{if(mobileTab===button.dataset.tab)return;mobileTab=button.dataset.tab;renderGame();scrollTo({top:0})});
}
const wideBoard=matchMedia('(min-width: 1051px)'),narrowScreen=matchMedia('(max-width: 760px)');
for(const query of [wideBoard,narrowScreen])query.addEventListener('change',()=>{if(state?.status==='playing')renderGame()});
// Raccourci clavier : R lance les dés quand c'est possible.
document.addEventListener('keydown',event=>{if(event.key.toLowerCase()!=='r'||event.ctrlKey||event.metaKey||event.altKey||event.repeat)return;if(event.target.closest?.('input,select,textarea,dialog')||document.querySelector('.deal-backdrop'))return;const roll=document.querySelector('#roll');if(roll&&!roll.disabled){event.preventDefault();roll.click()}});
// Onglet en arrière-plan : le titre prévient quand c'est à toi de jouer.
const baseTitle=document.title;
function notifyTurn(before,after){const mine=s=>s?.status==='playing'&&s.players[s.turn]?.id===me?.id;if(!mine(after)||mine(before))return;if(document.hidden)document.title='🎲 À toi de jouer ! · Cité Capitale';if(narrowScreen.matches)navigator.vibrate?.([60,40,60])}
document.addEventListener('visibilitychange',()=>{if(!document.hidden)document.title=baseTitle});
window.addEventListener('storage',async event=>{if(event.key!=='cc_profile')return;try{me=(await api('me',{},true)).profile}catch{me=null}home()});
async function bootstrap(){try{me=(await api('me',{},true)).profile;storage.setItem('cc_profile',JSON.stringify(me));storage.removeItem('cc_token')}catch{me=null;storage.removeItem('cc_profile');storage.removeItem('cc_token')}const invite=new URLSearchParams(location.search).get('salon'),saved=invite||storage.getItem('cc_room');if(me&&saved){try{const x=await api('state',{code:saved},true);enterRoom(saved,x.state);version=x.version;return}catch{if(invite){try{const x=await api('join',{code:invite});enterRoom(invite,x.state);return}catch(e){msg(e.message)}}storage.removeItem('cc_room')}}render()}
bootstrap();
setInterval(tickClock,1000);
