import pg from 'pg';
import { randomBytes, randomInt, createHash } from 'node:crypto';
import { applyCommand } from '../src/engine.js';
const { Pool }=pg; let pool;
const db=()=>pool??=(new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?.includes('localhost')?false:{rejectUnauthorized:true},max:3}));
let schemaPromise;
async function schema(){schemaPromise??=db().query(`CREATE TABLE IF NOT EXISTS profiles(id text PRIMARY KEY, pseudo text UNIQUE NOT NULL, token text UNIQUE NOT NULL, points integer NOT NULL DEFAULT 0, wins integer NOT NULL DEFAULT 0, games integer NOT NULL DEFAULT 0); CREATE UNIQUE INDEX IF NOT EXISTS profiles_pseudo_lower_unique ON profiles (lower(pseudo)); CREATE TABLE IF NOT EXISTS sessions(token_hash text PRIMARY KEY, profile_id text NOT NULL REFERENCES profiles(id), created_at timestamptz NOT NULL DEFAULT now()); CREATE TABLE IF NOT EXISTS rooms(code text PRIMARY KEY, host_id text NOT NULL, status text NOT NULL, state jsonb NOT NULL, version integer NOT NULL DEFAULT 0, updated_at timestamptz NOT NULL DEFAULT now());`).catch(e=>{schemaPromise=null;throw e});await schemaPromise}
const json=(res,status,obj)=>{res.statusCode=status;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(obj));};
const cookieName='cc_session';
const cookieToken=req=>{const match=String(req.headers.cookie||'').match(/(?:^|;\s*)cc_session=([^;]+)/);return match?.[1]||null};
const sessionHash=token=>createHash('sha256').update(token).digest('hex');
function sessionCookie(req,res,token){const secure=process.env.VERCEL==='1'||String(req.headers['x-forwarded-proto']||'').split(',')[0]==='https';res.setHeader('Set-Cookie',`${cookieName}=${token||''}; Path=/; HttpOnly; SameSite=Lax; ${secure?'Secure; ':''}${token?'Max-Age=2592000':'Max-Age=0'}`)}
const code=()=>randomBytes(3).toString('hex').toUpperCase(); const id=()=>randomBytes(12).toString('hex');
async function handler(req,res){try{await schema();let action=req.method==='GET'?new URL(req.url,'http://localhost').searchParams.get('action'):null;let body={};if(req.method==='POST'){if(req.body&&typeof req.body==='object')body=req.body;else{let chunks=[];for await(const c of req)chunks.push(c);body=JSON.parse(Buffer.concat(chunks).toString()||'{}')}action=body.action}const token=cookieToken(req);let profile=token?(await db().query('SELECT p.id,p.pseudo,p.points,p.wins,p.games FROM sessions s JOIN profiles p ON p.id=s.profile_id WHERE s.token_hash=$1 AND s.created_at>now()-interval \'30 days\'',[sessionHash(token)])).rows[0]:null;
 if(action==='profile'){let pseudo=String(body.pseudo||'').trim().slice(0,20);if(pseudo.length<2)return json(res,400,{error:'Le pseudo doit contenir au moins 2 caractères.'});let recovery=randomBytes(24).toString('hex'),session=randomBytes(32).toString('hex'),client=await db().connect();try{await client.query('BEGIN');let row=(await client.query('INSERT INTO profiles(id,pseudo,token) VALUES($1,$2,$3) RETURNING id,pseudo,points,wins,games',[id(),pseudo,sessionHash(recovery)])).rows[0];await client.query('INSERT INTO sessions(token_hash,profile_id) VALUES($1,$2)',[sessionHash(session),row.id]);await client.query('COMMIT');sessionCookie(req,res,session);return json(res,200,{profile:row,recovery})}catch(e){await client.query('ROLLBACK');if(e.code==='23505')return json(res,409,{error:'Ce pseudo est déjà réservé.'});throw e}finally{client.release()}}
 if(action==='resume'){let pseudo=String(body.pseudo||''),recovery=String(body.recovery||'');let row=(await db().query('SELECT id,pseudo,points,wins,games FROM profiles WHERE token=$1 AND lower(pseudo)=lower($2)',[sessionHash(recovery),pseudo])).rows[0];if(!row)return json(res,403,{error:'Code de reprise invalide.'});let session=randomBytes(32).toString('hex');await db().query('INSERT INTO sessions(token_hash,profile_id) VALUES($1,$2)',[sessionHash(session),row.id]);sessionCookie(req,res,session);return json(res,200,{profile:row})}
 if(action==='me')return profile?json(res,200,{profile}):json(res,401,{error:'Session expirée.'});
 if(action==='logout'){if(token)await db().query('DELETE FROM sessions WHERE token_hash=$1',[sessionHash(token)]);sessionCookie(req,res,null);return json(res,200,{ok:true})}
 if(action==='leaderboard'){let rows=(await db().query('SELECT pseudo,points,wins,games FROM profiles ORDER BY points DESC,wins DESC LIMIT 20')).rows;return json(res,200,{leaderboard:rows})}
 if(!profile)return json(res,401,{error:'Choisis un pseudo pour continuer.'});
 if(action==='create'){let roomCode=code(),state={status:'lobby',host:profile.id,settings:{minutes:body.minutes||60,randomStart:true},players:[{id:profile.id,name:profile.pseudo,color:'#e7bf62',cash:1500,pos:0,bankrupt:false}],board:[],phase:'lobby',turn:0,round:0,log:[{text:`${profile.pseudo} a créé le salon.`,icon:'✦'}],startedAt:null};return await db().query('INSERT INTO rooms(code,host_id,status,state) VALUES($1,$2,$3,$4)',[roomCode,profile.id,'lobby',JSON.stringify(state)]).then(()=>json(res,200,{code:roomCode,state}))}
 if(action==='join'){let c=String(body.code||'').toUpperCase(),client=await db().connect();try{await client.query('BEGIN');let q=await client.query('SELECT * FROM rooms WHERE code=$1 FOR UPDATE',[c]);let room=q.rows[0];if(!room){await client.query('ROLLBACK');return json(res,404,{error:'Salon introuvable.'})}let state=room.state;if(state.status!=='lobby'){await client.query('ROLLBACK');return json(res,409,{error:'La partie a déjà commencé.'})}if(state.players.some(p=>p.id===profile.id)){await client.query('COMMIT');return json(res,200,{code:c,state})}if(state.players.length>=6){await client.query('ROLLBACK');return json(res,409,{error:'Ce salon est complet.'})}state.players.push({id:profile.id,name:profile.pseudo,color:['#73c5ab','#e89077','#a98bdd','#72a9d6','#dc769b'][state.players.length-1],cash:1500,pos:0,bankrupt:false});state.log.unshift({text:`${profile.pseudo} rejoint la partie.`,icon:'✦'});await client.query('UPDATE rooms SET state=$1,version=version+1,updated_at=now() WHERE code=$2',[JSON.stringify(state),c]);await client.query('COMMIT');return json(res,200,{code:c,state})}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
 if(action==='state'){let c=String(new URL(req.url,'http://localhost').searchParams.get('code')||'').toUpperCase();let room=(await db().query('SELECT state,version FROM rooms WHERE code=$1',[c])).rows[0];if(!room)return json(res,404,{error:'Salon introuvable.'});if(!room.state.players.some(p=>p.id===profile.id))return json(res,403,{error:'Tu ne fais pas partie de ce salon.'});return json(res,200,{state:room.state,version:room.version})}
 if(action==='command'){const c=String(body.code||'').toUpperCase();const client=await db().connect();try{await client.query('BEGIN');let q=await client.query('SELECT * FROM rooms WHERE code=$1 FOR UPDATE',[c]);if(!q.rows[0]){await client.query('ROLLBACK');return json(res,404,{error:'Salon introuvable.'})}let state=q.rows[0].state;if(!state.players.some(x=>x.id===profile.id)){await client.query('ROLLBACK');return json(res,403,{error:'Tu ne fais pas partie du salon.'})}if(body.version!==undefined&&Number(body.version)!==q.rows[0].version){await client.query('ROLLBACK');return json(res,409,{error:'La partie a évolué. Actualisation…'})}let cmd=body.command,wasFinished=state.status==='finished';try{applyCommand(state,profile.id,cmd,body,['roll','timeout'].includes(cmd)?[randomInt(1,7),randomInt(1,7)]:undefined)}catch(e){await client.query('ROLLBACK');return json(res,400,{error:e.message})}if(!wasFinished&&state.status==='finished'&&state.results){for(let result of state.results)await client.query('UPDATE profiles SET points=points+$1,games=games+1,wins=wins+$2 WHERE id=$3',[result.points,result.id===state.results[0].id?1:0,result.id])}let v=q.rows[0].version+1;await client.query('UPDATE rooms SET state=$1,status=$2,version=$3,updated_at=now() WHERE code=$4',[JSON.stringify(state),state.status,v,c]);await client.query('COMMIT');return json(res,200,{state,version:v});}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
 return json(res,400,{error:'Action inconnue.'})
 }catch(e){console.error(e);return json(res,500,{error:process.env.DATABASE_URL?'Erreur serveur.':'Configure DATABASE_URL pour la persistance.'})}}
export default handler;
